//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gps
    {
        public int id { get; set; }
        public int numeroZona { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
