//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reclamo()
        {
            this.Historial = new HashSet<Historial>();
            this.TipoReclamo = new HashSet<TipoReclamo>();
        }
    
        public int numero { get; set; }
        public string usuarioNombre { get; set; }
        public int nroCuadrilla { get; set; }
        public int nroZona { get; set; }
        public string observacionCuadrilla { get; set; }
        public System.DateTime fechayhora { get; set; }
        public System.Data.Entity.Spatial.DbGeography longitud { get; set; }
        public System.Data.Entity.Spatial.DbGeography latitud { get; set; }
        public string estado { get; set; }
    
        public virtual Cuadrilla Cuadrilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial> Historial { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Zona Zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoReclamo> TipoReclamo { get; set; }
    }
}
